// <auto-generated />
using System;
using FinanceSystem_Dotnet.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceSystem_Dotnet.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Department", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.HasIndex("ManagerName")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploaderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UploaderName");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Fulfilled")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorName");

                    b.HasIndex("TransactionTypeName");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.TransactionDocument", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AttachedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId", "DocumentId");

                    b.HasIndex("AttachedBy");

                    b.HasIndex("DocumentId");

                    b.ToTable("TransactionDocument", (string)null);
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.TransactionForward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ForwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverComment")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Seen")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderComment")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverName");

                    b.HasIndex("SenderName");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionForwards");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.TransactionType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.HasIndex("CreatorName");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.User", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.HasIndex("DepartmentName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Department", b =>
                {
                    b.HasOne("FinanceSystem_Dotnet.Models.User", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("FinanceSystem_Dotnet.Models.Department", "ManagerName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Document", b =>
                {
                    b.HasOne("FinanceSystem_Dotnet.Models.User", "Uploader")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploaderName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Transaction", b =>
                {
                    b.HasOne("FinanceSystem_Dotnet.Models.User", "Creator")
                        .WithMany("CreatedTransactions")
                        .HasForeignKey("CreatorName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceSystem_Dotnet.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.TransactionDocument", b =>
                {
                    b.HasOne("FinanceSystem_Dotnet.Models.User", "AttachedByUser")
                        .WithMany()
                        .HasForeignKey("AttachedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceSystem_Dotnet.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceSystem_Dotnet.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachedByUser");

                    b.Navigation("Document");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.TransactionForward", b =>
                {
                    b.HasOne("FinanceSystem_Dotnet.Models.User", "Receiver")
                        .WithMany("ReceivedForwards")
                        .HasForeignKey("ReceiverName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceSystem_Dotnet.Models.User", "Sender")
                        .WithMany("SentForwards")
                        .HasForeignKey("SenderName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceSystem_Dotnet.Models.Transaction", "Transaction")
                        .WithMany("Forwards")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.TransactionType", b =>
                {
                    b.HasOne("FinanceSystem_Dotnet.Models.User", "Creator")
                        .WithMany("CreatedTransactionTypes")
                        .HasForeignKey("CreatorName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.User", b =>
                {
                    b.HasOne("FinanceSystem_Dotnet.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.Transaction", b =>
                {
                    b.Navigation("Forwards");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceSystem_Dotnet.Models.User", b =>
                {
                    b.Navigation("CreatedTransactionTypes");

                    b.Navigation("CreatedTransactions");

                    b.Navigation("ManagedDepartment")
                        .IsRequired();

                    b.Navigation("ReceivedForwards");

                    b.Navigation("SentForwards");

                    b.Navigation("UploadedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
